OT98-32: Endpoint de Eliminar usuario
alkemyTech/OT-98-Server pull request #31
Opened 2021-11-04 18:02 UTC by matiasutn2019

Methods added to controller, service & repository layers to delete a user by his id. Also exception class created to handle the absense of the user's record.

2021-11-04 18:16 UTC, mkain0 requested changes
@matiasutn2019 Revisa los comentarios y fijate que esta faltando la Collection de Postman con una request example del delete.

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new  ResponseEntity<>(id, HttpStatus.OK);
Como no hay body, deberíamos devolver un 204.

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  public IUserService iUserService;
Siguiendo el formato del proyecto, la interface debería ser IDeleteUserService y la variable deleteUserService.

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  public ResponseEntity<Long> deleteUserById(@PathVariable Long id) throws UserNotFoundException {
TRIVIAL: lo renombraria a deleteBy(....)

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +  public ResponseEntity<?> handleUserNotFoundException(HttpServletRequest request,
Evitaría crear esta custom exception y reutilizaría EntityNotFoundException. 

Por otro lado, estaba mirando el método del controllerAdvice para esa exception y los HTTP status code estan mal, deberia ser 404, no 400. Podrías modificarlo como parte de tu PR?

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
Reutilizaria EntityNotFoundException

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/IUserRepository.java
> +  void deleteUserById(Long id);
El borrado debe ser lógico según el scope del ticket. Lo que implica buscar el registro en la base de datos, setear el softDelete=true y después guardar el registro actualizado.

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IUserService.java
> +  User getUserById(Long id);
Este método no debería ser parte de la interface. La tarea solamente pide borrar, por lo tanto solo necesito un deleteBy(...)

2021-11-04 18:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +  }
Este método no debería ser expuesto por la interface. Pode mantenerlo como privado o directamente reemplazar este código en la linea 160.

2021-11-04 18:40 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new  ResponseEntity<>(id, HttpStatus.OK);
done

2021-11-04 18:45 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  public IUserService iUserService;
done

2021-11-04 18:46 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  public ResponseEntity<Long> deleteUserById(@PathVariable Long id) throws UserNotFoundException {
done

2021-11-04 18:46 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +  public ResponseEntity<?> handleUserNotFoundException(HttpServletRequest request,
ok

2021-11-04 18:51 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
ok

2021-11-04 19:14 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/service/abstraction/IUserService.java
> +  User getUserById(Long id);
done

2021-11-04 19:34 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +  }
done

2021-11-04 20:26 UTC, matiasutn2019 commented on src/main/java/com/alkemy/ong/repository/IUserRepository.java
> +  void deleteUserById(Long id);
done

2021-11-05 01:16 UTC, mkain0 commented
@matiasutn2019 chequeo con vos por las dudas... veo que todos los comentarios dicen done, pero no veo ningún commit pusheado. Se te olvidó pushear? o todavía estas trabajando en los comentarios? Cualquier cosa hace click en el botón de request review cuando este listo. Gracias!

2021-11-05 01:44 UTC, matiasutn2019 commented
me falta el postman todavía

2021-11-05 20:13 UTC, mkain0 approved these changes

2021-11-05 20:14 UTC, merged