OT98 40: endpoint Listado de Categorías
alkemyTech/OT-98-Server pull request #46
Opened 2021-11-10 23:24 UTC by alexB0999

List of categories enpoint implemented.
IListCategoryService was developed and implemented by CategoryServiceImpl. 
Model Mapper dependency was added to pom.xml.

2021-11-11 14:04 UTC, mkain0 requested changes
@alexB0999 falta el Postman collection actualizado.

2021-11-11 14:04 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +    ModelMapper modelMapper = new ModelMapper();
La instancia de ModelMapper es muy costosa, por lo tanto esto debería estar en una configuration class o declarado en el ConvertUtil.

2021-11-11 14:04 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +    List<Category> categories = categoryRepository.findAll();
Solo se deben listar aquellas donde el softDelete=false.

2021-11-11 14:04 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +    return listCategoryResponses;
Revisaste como luce el json response cuando creas la response de esta forma?

2021-11-11 14:07 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  public ResponseEntity<List<ListCategoryResponse>> findAllCategories() {
Falta agregar el endpoint al SecurityConfig.

2021-11-12 19:28 UTC, mkain0 commented on src/main/java/com/alkemy/ong/config/SecurityConfig.java
> +        .antMatchers(HttpMethod.POST, "/categories/**")
Por qué este cambio?

2021-11-12 19:34 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +    }
Estas exceptions solo aplican para los find by ID. Los find all en REST no lanzan exceptions.

2021-11-12 19:36 UTC, mkain0 commented
@alexB0999 Mergeo este PR, pero le faltó el Postman Collection
https://github.com/alkemyTech/OT-98-Server/pull/46#pullrequestreview-803827972

2021-11-12 19:36 UTC, mkain0 approved these changes

2021-11-12 19:37 UTC, merged

2021-11-12 19:42 UTC, alexB0999 commented
Uuuy no me digas que faltó la Collection, si yo me traje los cambios, y vreeria que comitié la request que agregué tambien

2021-11-12 19:43 UTC, alexB0999 commented on src/main/java/com/alkemy/ong/config/SecurityConfig.java
> +        .antMatchers(HttpMethod.POST, "/categories/**")
Mala mia, lo hice para probar pero me olvidé de sacarlo 🤦‍♂️