OT98-96: Added authentication tests
alkemyTech/OT-98-Server pull request #47
Opened 2021-11-10 23:51 UTC by ignaciomontovio

COMO desarrollador
QUIERO disponer de tests de los endpoints de /authentication
PARA asegurar la integridad y funcionamiento del proyecto

Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

Evidencia:
![imagen](https://user-images.githubusercontent.com/49342337/141211994-0a9b7661-adce-410c-a5bc-223a0a35e71b.png)

2021-11-11 14:26 UTC, mkain0 requested changes
@ignaciomontovio Al ser test de integración, el JWT token debe salir del Login. Por lo tanto, antes tenes que ejecutar una request al Login con los datos de un User. Podes utilizar los datos de los Usuarios del data seeeder.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/LoginIntegrationTest.java
> +public class LoginIntegrationTest extends AbstractBaseIntegrationTest {
@ignaciomontovio Por favor revisa los test de esta clase, los test para este endpoint estan en UserAuthenticationIntegrationTest.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/MeIntegrationTest.java
> +public class MeIntegrationTest extends AbstractBaseIntegrationTest {
Dato que estos test corresponden a el servicio de la interfaz IAuthenticatedUserDetails, renombraria la clases a AuthenticatedUserDetailsIntegrationTest.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/MeIntegrationTest.java
> +  private IUserRepository userRepository;
Estas injectando el servicio real. Esto debería ser un mock.
Adicionalmente, este mock esta definido AbstractBaseIntegrationTest.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/MeIntegrationTest.java
> +  @Autowired
Este servicio no debe ser injectado porque es creado por el main.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/MeIntegrationTest.java
> +  @Autowired
Lo mismo acá, debería ser un mock.

2021-11-11 14:26 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/UserRegisterIntegrationTest.java
> +  public void shouldRegisterSuccessfully() {
Este test ya existe, es lo que esta haciendo en shouldReturnJwtToken.

2021-11-13 18:19 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/AuthenticatedUserDetailsIntegrationTest.java
> +    Assert.assertEquals("Ignacio", response.getBody().getFirstName());
@ignaciomontovio Para futuros test, podes utilizar assertNotNull para cosas como el response.getBody(). De esa forma si algo cambia y el test falla, en vez de tirar un NPE que puede venir de cualquier lado, lanzaría un assertFail.

2021-11-13 18:20 UTC, mkain0 approved these changes

2021-11-13 18:20 UTC, merged

2021-11-13 18:35 UTC, ignaciomontovio commented on src/test/java/com/alkemy/ong/integration/AuthenticatedUserDetailsIntegrationTest.java
> +    Assert.assertEquals("Ignacio", response.getBody().getFirstName());
Ok, es buena.