OT98-30:  Envio de email de Bienvenida
alkemyTech/OT-98-Server pull request #53
Opened 2021-11-15 16:23 UTC by OscarRuina

Summary:
 - minor changes to template.
 - add send email to register user.

2021-11-15 18:56 UTC, mkain0 requested changes

2021-11-15 18:56 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +      log.info(e.getMessage());
MINOR: lo logearia como un warning.

2021-11-15 18:56 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +      emailHelper.send(new RegisterTemplateEmail(
Esto debería suceder después de hacer el save del user, ya que si algo falla al guardar el registro en la base datos, no tendría sentido enviar un mail que le de la bienvenida al sitio al user.

2021-11-15 18:56 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/mail/template/RegisterTemplateEmail.java
> +        + "\n" + organizationName
El organizationName esta hardcodeado en el WELCOME_TEXT, sería más conveniente hacer:

WELCOME_TEXT = "Welcome to {0}!"

MessageFormat.format(WELCOME_TEXT, organizationName)

2021-11-15 19:14 UTC, OscarRuina commented on src/main/java/com/alkemy/ong/common/mail/template/RegisterTemplateEmail.java
> +        + "\n" + organizationName
Arreglado

2021-11-15 19:14 UTC, OscarRuina commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +      emailHelper.send(new RegisterTemplateEmail(
Arreglado.

2021-11-15 20:32 UTC, mkain0 requested changes
@OscarRuina Este branch no pasa el build. Por favor, arreglar los test que estan fallando.

2021-11-15 20:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +    User save = userRepository.save(user);
Este bloque podría ser más legible si se refactoriza como:

 ```
 @Override
  @Transactional
  public UserRegisterResponse register(UserRegisterRequest registerRequest)
      throws EmailAlreadyExistException {
    if (userRepository.findByEmail(registerRequest.getEmail()) != null) {
      throw new EmailAlreadyExistException();
    }

    User user = userRepository.save(buildUser(registerRequest));
    sendEmail(registerRequest.getEmail());
    return convertUtils.toResponse(user, jwtUtil.generateToken(user));
  }

  private User buildUser(UserRegisterRequest registerRequest) {
    User user = new User();
    user.setFirstName(registerRequest.getFirstName());
    user.setLastName(registerRequest.getLastName());
    user.setEmail(registerRequest.getEmail());
    user.setPassword(bCryptPasswordEncoder.encode(registerRequest.getPassword()));
    List<Role> roles = new ArrayList<>();
    roles.add(roleService.findBy(ApplicationRole.USER.getFullRoleName()));
    user.setRoles(roles);
    return user;
  }

  private void sendEmail(String email) {
    try {
      OrganizationResponse organizationDetails = organizationService.getOrganizationDetails();
      emailHelper.send(new RegisterTemplateEmail(
          email,
          organizationDetails.getImage(),
          organizationDetails.getName(),
          organizationDetails.getAddress(),
          organizationDetails.getPhone()
      ));
    } catch (SendEmailException e) {
      log.warn(e.getMessage());
    }
  }
```

2021-11-15 20:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/mail/template/RegisterTemplateEmail.java
> +        + "\n" + organizationName
Esta linea es redundante porque el valor esta siendo utilizado en la linea 39.

2021-11-16 01:46 UTC, OscarRuina commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +    User save = userRepository.save(user);
Arreglado.

2021-11-16 01:46 UTC, OscarRuina commented on src/main/java/com/alkemy/ong/common/mail/template/RegisterTemplateEmail.java
> +        + "\n" + organizationName
Arreglado.

2021-11-16 01:46 UTC, OscarRuina commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +    User save = userRepository.save(user);
Arregle el test.

2021-11-16 13:53 UTC, mkain0 requested changes
@OscarRuina Este branch sigue sin compilar. Por favor, ejecutar mvn clean install antes de la próxima revisión.

2021-11-16 14:56 UTC, OscarRuina commented
> @OscarRuina Este branch sigue sin compilar. Por favor, ejecutar mvn clean install antes de la próxima revisión.

Listo, hice el merge con main e hice el mvn clean install y anda.

2021-11-16 16:15 UTC, mkain0 approved these changes

2021-11-16 16:16 UTC, merged