OT98-91: adding integration member file
alkemyTech/OT-98-Server pull request #77
Opened 2021-11-22 21:51 UTC by JoaquinAman

se agrego la carpeta de tests de member

2021-11-22 22:49 UTC, mkain0 requested changes

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/CreateMemberIntegrationTest.java
> +  public void shouldReturnForbbidenWhenUserIsNotUser() {
TYPO: Forbidden

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/CreateMemberIntegrationTest.java
> +package com.alkemy.ong.integration.member;
Falta aplicar Style en este archivo.

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/DeleteMemberIntegrationTest.java
> +  public void shouldReturnNotFoundWhenIdNotExist() {
MINOR: WhenIdDoesNotExist

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/DeleteMemberIntegrationTest.java
> +  public void shouldSoftDeleteAMemberSuccesfully() {
TYPO: Successfully

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/ListMemberIntegrationTest.java
> +  }
DUPLICATE CODE: el código no se debe copiar y pegar por todos lados. Por favor, extraer esto a un útil y reutilizar el util en los test de paginación existentes.

2021-11-22 22:49 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/member/UpdateMemberIntegrationTest.java
> +  public void shouldReturnNotFoundWhenIdNotExist() {
MINOR: WhenIdDoesNotExist

2021-11-23 03:17 UTC, JoaquinAman commented
requested changes fixed

2021-11-23 04:13 UTC, mkain0 requested changes

2021-11-23 04:13 UTC, mkain0 commented on src/test/java/com/alkemy/ong/common/ListTestUtils.java
> +
PaginationUtil sería más representativo. Los métodos de esta clase deberían ser static y debería tener un constructor privado.

Adicionalmente, no veo que se haya removido el código duplicado de las clases existentes.

2021-11-23 13:39 UTC, mkain0 approved these changes

2021-11-23 13:39 UTC, merged