OT98-89 Agregar documentación a Autenticación
alkemyTech/OT-98-Server pull request #78
Opened 2021-11-22 22:30 UTC by JoaquinAman

![evidencia ticket 89](https://user-images.githubusercontent.com/55667385/142944570-fab947c7-bbb4-4b69-9ac6-32a8b5f9b4ea.JPG)

Se agrego documentacion del endpoint de autenticacion

2021-11-22 22:37 UTC, mkain0 requested changes
@JoaquinAman El scope del ticket es para agregar documentación a todos los endpoints que incluyen /auth en la URL.

2021-11-22 22:40 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
>    public ResponseEntity<?> login(@RequestBody UserAuthenticationRequest userRequest)
La documentación no muestra la response body.

2021-11-23 20:20 UTC, JoaquinAman commented
fixing requested changes
adding documentatios annotations to UserController

2021-11-23 21:16 UTC, mkain0 approved these changes

2021-11-23 21:17 UTC, merged